Assignment 1 — Patient Clinical Data Analysis

Dataset
patient_clinical_data_raw.csv
Objective: You are working as a data analyst in a hospital. The hospital has provided a raw patient
dataset containing demographic, clinical, admission, and treatment information. Your task is to use
Pandas to clean, transform, analyze, and summarize the data.

Part A — Understanding the Dataset

1. Load the dataset into a Pandas DataFrame.

In [252]:
import pandas as pd 
import numpy as np 

df = pd.read_csv('../data/patient_clinical_data_raw.csv')

2. Display the first 10 and last 10 records.

In [253]:
df.head(10)

,Patient_ID,Age,Gender,Department,Blood_Pressure,Heart_Rate,Temperature,Cholesterol,Glucose,Diagnosis,Admission_Type,Length_of_Stay,Treatment_Cost,Readmission
0,P07402,58.0,Female,Orthopedics,119/73,64.0,100.0,197.0,60.0,Heart Disease,Referral,5,91183.33,No
1,P05835,NaN,Female,General Medicine,107/91,62.0,98.8,215.0,92.0,Migraine,Referral,5,71104.32,No
2,P02123,47.0,Male,Orthopedics,148/98,83.0,96.0,196.0,133.0,Fracture,Routine,7,135197.73,No
3,P08789,NaN,Male,Oncology,115/84,89.0,100.1,224.0,119.0,Hypertension,Referral,6,146462.06,No
4,P00305,47.0,Female,Orthopedics,128/62,77.0,100.3,184.0,113.0,Hypertension,Emergency,6,57510.66,No
5,P02532,31.0,Female,Oncology,104/85,99.0,96.3,196.0,86.0,Hypertension,Routine,5,128417.99,Yes
6,P02996,49.0,MALE,Neurology,118/83,108.0,99.4,192.0,166.0,Heart Disease,Routine,7,106428.84,No
7,P07660,32.0,Female,Pediatrics,122/89,64.0,97.9,186.0,101.0,Cancer,Routine,5,126644.27,No
8,P08225,64.0,Male,Neurology,161/100,61.0,98.5,178.0,85.0,Cancer,Emergency,7,76285.34,No
9,P04449,56.0,Male,General Medicine,102/76,83.0,97.9,263.0,147.0,Migraine,Routine,6,150822.91,No

In [254]:
df.tail(10)

,Patient_ID,Age,Gender,Department,Blood_Pressure,Heart_Rate,Temperature,Cholesterol,Glucose,Diagnosis,Admission_Type,Length_of_Stay,Treatment_Cost,Readmission
10090,P08323,80.0,Female,cardiology,143/68,95.0,98.5,209.0,96.0,Migraine,Referral,6,113362.17,No
10091,P05579,NaN,Male,Orthopedics,130/70,55.0,98.6,210.0,136.0,Migraine,Emergency,6,68281.49,No
10092,P04427,54.0,Female,Neurology,126/93,82.0,98.5,168.0,147.0,Asthma,Referral,4,106702.38,No
10093,P00467,59.0,Female,Cardiology,126/85,81.0,98.4,212.0,150.0,Heart Disease,Routine,6,62179.59,No
10094,P06266,50.0,Female,Pediatrics,123/93,82.0,98.7,185.0,60.0,Infection,Routine,6,108423.54,Yes
10095,P05735,37.0,Female,cardiology,155/104,56.0,101.2,173.0,60.0,Cancer,Emergency,7,158883.26,No
10096,P05192,47.0,Female,Orthopedics,121/62,78.0,97.8,168.0,NaN,Infection,Routine,5,103698.89,No
10097,P05391,35.0,Male,General Medicine,108/49,74.0,99.3,156.0,140.0,Diabetes,Referral,7,129075.91,No
10098,P00861,51.0,Female,Pediatrics,95/83,86.0,98.6,258.0,110.0,Heart Disease,Referral,4,100906.67,No
10099,P07271,17.0,Male,Oncology,96/63,81.0,99.0,165.0,114.0,Heart Disease,Referral,5,121905.87,No

3. Find the number of rows and columns.

In [255]:
df.shape

(10100, 14)

4. Display the column names and their data types.

In [256]:
df.columns

Index(['Patient_ID', 'Age', 'Gender', 'Department', 'Blood_Pressure',
       'Heart_Rate', 'Temperature', 'Cholesterol', 'Glucose', 'Diagnosis',
       'Admission_Type', 'Length_of_Stay', 'Treatment_Cost', 'Readmission'],
      dtype='object')

5. Generate a statistical summary of the numerical columns.

In [257]:
df.describe()

,Age,Heart_Rate,Temperature,Cholesterol,Glucose,Length_of_Stay,Treatment_Cost
count,9798.000000,9798.000000,9796.000000,9797.000000,9798.000000,10100.000000,10100.000000
mean,47.418249,77.927740,98.399490,195.187098,106.199939,5.033960,100538.421836
std,18.021377,11.914117,1.199324,34.777238,28.656813,1.996912,42516.545663
min,-5.000000,45.000000,95.000000,100.000000,60.000000,1.000000,13492.020000
25%,35.000000,70.000000,97.600000,172.000000,85.000000,4.000000,68704.152500
50%,47.000000,78.000000,98.400000,195.000000,105.000000,5.000000,94104.265000
75%,60.000000,86.000000,99.200000,219.000000,126.000000,6.000000,125074.220000
max,150.000000,122.000000,102.900000,326.000000,209.000000,14.000000,315212.620000

6. Identify the number of unique values in each column.

In [258]:

df.nunique()

Patient_ID        10000
Age                  92
Gender                5
Department            9
Blood_Pressure     3645
Heart_Rate           75
Temperature          76
Cholesterol         206
Glucose             145
Diagnosis             8
Admission_Type        3
Length_of_Stay       14
Treatment_Cost     9998
Readmission           2
dtype: int64

Part B — Data Cleaning

7. Identify all columns containing missing values.

In [259]:
df.isna().sum()

Patient_ID          0
Age               302
Gender              0
Department          0
Blood_Pressure      0
Heart_Rate        302
Temperature       304
Cholesterol       303
Glucose           302
Diagnosis           0
Admission_Type      0
Length_of_Stay      0
Treatment_Cost      0
Readmission         0
dtype: int64

8. Calculate the percentage of missing values in each column.

In [260]:
missing_pct = df.isna().mean() * 100
missing_pct = missing_pct.round(2).sort_values(ascending=False)
missing_pct

Temperature       3.01
Cholesterol       3.00
Age               2.99
Heart_Rate        2.99
Glucose           2.99
Patient_ID        0.00
Gender            0.00
Department        0.00
Blood_Pressure    0.00
Diagnosis         0.00
Admission_Type    0.00
Length_of_Stay    0.00
Treatment_Cost    0.00
Readmission       0.00
dtype: float64

9. Handle missing values in the numerical columns appropriately.

In [261]:

num_cols = df.select_dtypes(include=[np.number]).columns
missing_before = df[num_cols].isna().sum()
median_values = df[num_cols].median()
df[num_cols] = df[num_cols].fillna(median_values)
missing_after = df[num_cols].isna().sum()
pd.concat([missing_before, median_values, missing_after], axis=1, keys=['missing_before','median','missing_after'])

                missing_before     median  missing_after
Age                        302     47.000              0
Heart_Rate                 302     78.000              0
Temperature                304     98.400              0
Cholesterol                303    195.000              0
Glucose                    302    105.000              0
Length_of_Stay               0      5.000              0
Treatment_Cost               0  94104.265              0

10. Identify and remove duplicate records.

In [262]:
# 10. Identify and remove duplicate records
dup_mask = df.duplicated()
total_duplicates = dup_mask.sum()
print(f"Total duplicate rows: {total_duplicates}")
if total_duplicates > 0:
    print('\nSample duplicate rows (first 10):')
    display(df[dup_mask].head(10))
    shape_before = df.shape
    df.drop_duplicates(inplace=True)
    df.reset_index(drop=True, inplace=True)
    shape_after = df.shape
    print(f"\nShape before: {shape_before}\nShape after:  {shape_after}")
else:
    print('No duplicate rows found.')

Total duplicate rows: 100

Sample duplicate rows (first 10):

,Patient_ID,Age,Gender,Department,Blood_Pressure,Heart_Rate,Temperature,Cholesterol,Glucose,Diagnosis,Admission_Type,Length_of_Stay,Treatment_Cost,Readmission
919,P00800,48.0,Female,Oncology,121/74,91.0,96.9,241.0,122.0,Asthma,Emergency,3,61810.88,No
980,P01057,47.0,Female,Pediatrics,164/84,85.0,98.7,210.0,81.0,Infection,Emergency,5,86453.79,No
1062,P02305,83.0,Male,Neurology,141/74,84.0,98.9,100.0,86.0,Cancer,Emergency,7,103400.47,Yes
1119,P02593,47.0,Female,Oncology,146/82,71.0,98.6,173.0,106.0,Diabetes,Referral,7,151377.19,No
1136,P02928,51.0,Male,Orthopedics,112/63,63.0,98.2,198.0,82.0,Fracture,Emergency,6,155770.34,No
1185,P00108,51.0,Male,Cardiology,84/82,87.0,98.8,203.0,100.0,Heart Disease,Emergency,5,104717.32,Yes
1340,P01316,24.0,Male,Pediatrics,140/79,86.0,98.9,232.0,112.0,Migraine,Emergency,4,49645.03,No
1443,P05548,56.0,Male,Cardiology,100/103,87.0,97.1,194.0,60.0,Migraine,Emergency,7,137167.71,No
1659,P00036,26.0,Female,Orthopedics,150/100,65.0,99.0,215.0,159.0,Diabetes,Emergency,3,94648.40,No
1777,P02021,49.0,Female,Pediatrics,111/87,79.0,100.2,224.0,71.0,Asthma,Emergency,6,96577.34,No

Shape before: (10100, 14)
Shape after:  (10000, 14)

11. Check the Age column for invalid values.

In [263]:
df[df['Age'] < 1]

,Patient_ID,Age,Gender,Department,Blood_Pressure,Heart_Rate,Temperature,Cholesterol,Glucose,Diagnosis,Admission_Type,Length_of_Stay,Treatment_Cost,Readmission
682,P00684,-5.0,Male,General Medicine,117/77,55.0,98.5,146.0,154.0,Infection,Routine,2,52628.80,No
1214,P06801,-5.0,Male,General Medicine,145/64,90.0,98.7,157.0,162.0,Cancer,Referral,4,78841.67,No
1413,P08175,-5.0,Male,Orthopedics,127/92,74.0,98.4,189.0,99.0,Diabetes,Emergency,3,68268.64,Yes
2090,P01771,-5.0,Female,Cardiology,134/77,77.0,100.0,189.0,131.0,Asthma,Referral,8,95832.96,No
2454,P02920,-5.0,Male,Cardiology,157/76,86.0,98.7,139.0,82.0,Heart Disease,Routine,3,42391.19,Yes
3774,P09773,-5.0,Female,Cardiology,118/62,97.0,98.4,171.0,124.0,Cancer,Emergency,10,162966.28,No
4311,P02156,-5.0,Male,Cardiology,153/78,63.0,98.0,166.0,60.0,Hypertension,Routine,7,186112.26,Yes
5834,P08060,-5.0,Male,Cardiology,149/92,92.0,99.6,201.0,134.0,Heart Disease,Emergency,7,197002.43,No
6147,P06021,-5.0,Male,Pediatrics,107/82,84.0,98.8,178.0,111.0,Infection,Routine,4,116787.01,No
8487,P03639,-5.0,Male,Oncology,139/74,57.0,99.9,206.0,105.0,Infection,Emergency,6,146178.40,No

12. Correct or handle patients whose age is outside a reasonable range.

In [264]:
# 12. Correct or handle patients whose age is outside a reasonable range
age_col = 'Age'
if age_col not in df.columns:
    print(f"Column '{age_col}' not found in dataframe.")
else:
    # Identify invalid ages (negative or unrealistically high)
    invalid_mask = (df[age_col] < 0) | (df[age_col] > 120)
    total_invalid = invalid_mask.sum()
    print(f"Total invalid age entries: {total_invalid}")
    if total_invalid > 0:
        print('\nSample invalid age rows:')
        display(df.loc[invalid_mask].head(10))
        # Set invalid ages to NaN for safe imputation
        df.loc[invalid_mask, age_col] = np.nan
        # Impute with median age (rounded to int)
        median_age = int(df[age_col].median(skipna=True))
        df[age_col] = df[age_col].fillna(median_age).astype(int)
        print(f"\nReplaced invalid ages with median age: {median_age}")
        remaining_invalid = ((df[age_col] < 0) | (df[age_col] > 120)).sum()
        print(f"Invalid age entries after correction: {remaining_invalid}")
    else:
        print('No invalid ages found (within 0-120).')

Total invalid age entries: 15

Sample invalid age rows:

,Patient_ID,Age,Gender,Department,Blood_Pressure,Heart_Rate,Temperature,Cholesterol,Glucose,Diagnosis,Admission_Type,Length_of_Stay,Treatment_Cost,Readmission
39,P00304,150.0,Female,General Medicine,116/93,94.0,98.5,207.0,152.0,Migraine,Referral,5,81852.40,No
399,P07151,150.0,Male,Neurology,141/77,68.0,98.4,195.0,85.0,Cancer,Routine,4,69542.41,No
682,P00684,-5.0,Male,General Medicine,117/77,55.0,98.5,146.0,154.0,Infection,Routine,2,52628.80,No
1214,P06801,-5.0,Male,General Medicine,145/64,90.0,98.7,157.0,162.0,Cancer,Referral,4,78841.67,No
1413,P08175,-5.0,Male,Orthopedics,127/92,74.0,98.4,189.0,99.0,Diabetes,Emergency,3,68268.64,Yes
1612,P00555,150.0,Female,Pediatrics,129/54,53.0,97.6,223.0,132.0,Heart Disease,Routine,5,85293.98,No
2090,P01771,-5.0,Female,Cardiology,134/77,77.0,100.0,189.0,131.0,Asthma,Referral,8,95832.96,No
2454,P02920,-5.0,Male,Cardiology,157/76,86.0,98.7,139.0,82.0,Heart Disease,Routine,3,42391.19,Yes
3774,P09773,-5.0,Female,Cardiology,118/62,97.0,98.4,171.0,124.0,Cancer,Emergency,10,162966.28,No
4311,P02156,-5.0,Male,Cardiology,153/78,63.0,98.0,166.0,60.0,Hypertension,Routine,7,186112.26,Yes

Replaced invalid ages with median age: 47
Invalid age entries after correction: 0

13. Identify inconsistent values in categorical columns such as Gender and Department.

In [265]:

df['Gender'].unique()
print(f"Unique values in 'Gender' column: {df['Gender'].unique()}")
s = df['Gender'].astype(str).str.strip().str.lower()
mapping = {
    'male': 'Male',
    'm': 'Male',
    'female': 'Female',
    'f': 'Female',
    'other': 'Other',
    'o': 'Other'
}
df['Gender'] = s.map(mapping).fillna('Other')   
print(f"Unique values in 'Gender' column after standardization: {df['Gender'].unique()}")

Unique values in 'Gender' column: ['Female' 'Male' 'MALE' 'male' ' FEMALE ']
Unique values in 'Gender' column after standardization: ['Female' 'Male']

In [266]:
df['Department'].unique()
df['Department'] = df['Department'].astype(str).str.strip().str.title()
print(f"Unique values in 'Department' column after standardization: {df['Department'].unique()}")

Unique values in 'Department' column after standardization: ['Orthopedics' 'General Medicine' 'Oncology' 'Neurology' 'Pediatrics'
 'Cardiology']

14. Standardize these categorical values.

In [267]:
s = df['Gender'].astype(str).str.strip().str.lower()
print(s.unique())
mapping = {
    'male':'M',
    'female':'F'  
}
df['Gender'] = s.map(mapping)
print(f"Unique values in 'Gender' column after mapping: {df['Gender'].unique()}")

['female' 'male']
Unique values in 'Gender' column after mapping: ['F' 'M']

Part C — Data Transformation
15. Create a new column called Age_Group:
< 18 Child
18–40 Young Adult
41–60 Middle Age
> 60 Senior

In [268]:
import numpy as np
df['Age'] = pd.to_numeric(df['Age'], errors='coerce')
df['Age_Group'] = np.nan
for i in range(len(df)):
    age = df.loc[i, 'Age']
    if pd.isna(age):
        df.loc[i, 'Age_Group'] = np.nan
    elif age < 18:
        df.loc[i, 'Age_Group'] = 'Child'
    elif age <= 40:
        df.loc[i, 'Age_Group'] = 'Young Adult'
    elif age <= 60:
        df.loc[i, 'Age_Group'] = 'Middle Aged'
    else:
        df.loc[i, 'Age_Group'] = 'Senior'

/var/folders/0f/pwtnxcjd59gb4c95ngqx5rq80000gn/T/ipykernel_29129/4173107873.py:13: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'Middle Aged' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[i, 'Age_Group'] = 'Middle Aged'

In [269]:
df[['Age', 'Age_Group']].head(10)

   Age    Age_Group
0   58  Middle Aged
1   47  Middle Aged
2   47  Middle Aged
3   47  Middle Aged
4   47  Middle Aged
5   31  Young Adult
6   49  Middle Aged
7   32  Young Adult
8   64       Senior
9   56  Middle Aged

In [270]:
 #16. Separate Blood_Pressure into Systolic and Diastolic

df[['systolic', 'diastolic']] = df['Blood_Pressure'].str.split('/', expand=True)

In [271]:
df[['systolic', 'diastolic','Blood_Pressure']].head(10)

  systolic diastolic Blood_Pressure
0      119        73         119/73
1      107        91         107/91
2      148        98         148/98
3      115        84         115/84
4      128        62         128/62
5      104        85         104/85
6      118        83         118/83
7      122        89         122/89
8      161       100        161/100
9      102        76         102/76

17. Create a High_Risk column based on suitable clinical conditions.

In [279]:

Age_Group = df['Age_Group'] == 'Senior'
Diagnosis = df['Diagnosis'].astype(str).str.strip().str.title().isin(['Cancer','Heart Disease'])
Emergency = df['Admission_Type'].astype(str).str.strip().str.lower() == 'emergency'

high_risk = Age_Group | Diagnosis | Emergency

df['High_Risk'] = high_risk.map({True: 'Yes', False: 'No'})

18. Create a Cost_Per_Day column using treatment cost and length of stay.

In [284]:
cost = df['Treatment_Cost'].astype(int)
days = df['Length_of_Stay'].astype(int)
df['Cost_Per_Day'] = cost / days
df['Cost_Per_Day'] = df['Cost_Per_Day'].round(2)
df.head()

,Patient_ID,Age,Gender,Department,Blood_Pressure,Heart_Rate,Temperature,Cholesterol,Glucose,Diagnosis,Admission_Type,Length_of_Stay,Treatment_Cost,Readmission,Age_Group,systolic,diastolic,High_Risk,Cost_Per_Day
0,P07402,58,F,Orthopedics,119/73,64.0,100.0,197.0,60.0,Heart Disease,Referral,5,91183.33,No,Middle Aged,119,73,Yes,18236.60
1,P05835,47,F,General Medicine,107/91,62.0,98.8,215.0,92.0,Migraine,Referral,5,71104.32,No,Middle Aged,107,91,No,14220.80
2,P02123,47,M,Orthopedics,148/98,83.0,96.0,196.0,133.0,Fracture,Routine,7,135197.73,No,Middle Aged,148,98,No,19313.86
3,P08789,47,M,Oncology,115/84,89.0,100.1,224.0,119.0,Hypertension,Referral,6,146462.06,No,Middle Aged,115,84,No,24410.33
4,P00305,47,F,Orthopedics,128/62,77.0,100.3,184.0,113.0,Hypertension,Emergency,6,57510.66,No,Middle Aged,128,62,Yes,9585.00